## Go的异常机制

Go的异常同c/c++ 会立刻让程序崩溃，但是Go的异常捕获不同于一般语言的try-catch机制，而是发生异常后，从异常的栈中恢复出来。

## panic函数与recover函数

> panic函数

调用一个panic函数会导致一个异常。定义如下：

```go
func panic(v any)
```

panic函数会打印出传入panic函数的值与发生异常的位置。

> recover函数

一般recover函数与defer一起使用，recover函数能获取到panic的输入值并且将程序从异常中恢复出来，当未发生异常时，recover返回nil。定义如下：

```go
func recover() any
```

* 某函数中defer了的函数在该函数发生异常后都会被调用，所以一般将recover放入到某个函数中并结合defer来使用。
* 虽然在当前栈中defer了的函数在发生异常后都会被调用，但是如果异常后没有recover，程序将会在该函数终结。